### ISSUE TITLE
Error in xtractor.load_state_dict

### ISSUE THREAD

**Issue by kuruhuru** [deep-privacy/sidekit#1]
Hello!
I tried to reproduce your example code (Downloaded model from https://github.com/deep-privacy/sidekit/releases/download/sidekit_v0.1/best_halp_clr_adam_aam0.2_30_b256_vox12.pt_epoch71)

model_path = './best_halp_clr_adam_aam0.2_30_b256_vox12.pt_epoch71'
device = 'cuda' if torch.cuda.is_available() else 'cpu'

model_config = torch.load(model_path, map_location=device)

model_opts = model_config['model_archi']
if 'embedding_size' not in model_opts:
    model_opts['embedding_size'] = 256
xtractor = Xtractor(model_config['speaker_number'],
                 model_archi=model_opts['model_type'],
                 loss=model_opts['loss']['type'],
                 embedding_size=model_opts['embedding_size'])

xtractor.load_state_dict(model_config['model_state_dict'], strict=True)

And I got the following:

RuntimeError                              Traceback (most recent call last)
[<ipython-input-52-e17faa220940>](https://localhost:8080/#) in <module>()
     12                  embedding_size=model_opts['embedding_size'])
     13 
---> 14 xtractor.load_state_dict(model_config['model_state_dict'], strict=True)
     15 xtractor = xtractor.to(device)
     16 xtractor.eval()

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in load_state_dict(self, state_dict, strict)
   1481         if len(error_msgs) > 0:
   1482             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1483                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1484         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1485 

RuntimeError: Error(s) in loading state_dict for Xtractor:
	size mismatch for stat_pooling.attention.0.weight: copying a param with shape torch.Size([128, 7680, 1]) from checkpoint, the shape in current model is torch.Size([128, 61440, 1]).
	size mismatch for stat_pooling.attention.4.weight: copying a param with shape torch.Size([2560, 128, 1]) from checkpoint, the shape in current model is torch.Size([20480, 128, 1]).
	size mismatch for stat_pooling.attention.4.bias: copying a param with shape torch.Size([2560]) from checkpoint, the shape in current model is torch.Size([20480]).

**Comment by pchampio** [comment]
This toolkit is in the process of been release.
If you use the commit: https://github.com/deep-privacy/sidekit/commit/4e5d66fbfb43b1ad4f5a43fa9274ac9010e4d782
loading this model should work.
For further release go to: https://git-lium.univ-lemans.fr/speaker/sidekit
